# Generated by Django 4.2.17 on 2025-01-26 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('beginning_balance', models.FloatField()),
                ('ending_balance', models.FloatField()),
            ],
        ),
    ]
