# Generated by Django 4.2.17 on 2025-01-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months',
            name='month',
        ),
        migrations.RemoveField(
            model_name='months',
            name='year',
        ),
    ]
