# Generated by Django 4.2.17 on 2025-01-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_pdf', '0003_months_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
