# Generated by Django 4.2.17 on 2025-01-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
